name: Validate

on:
  push:
  pull_request:

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3.0.2
      - name: 🏃 Hassfest validation
        uses: home-assistant/actions/hassfest@master

  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3.0.2
      - name: 🏃 HACS validation
        uses: hacs/action@main
        with:
          category: integration

  validate-homeassistant:
    strategy:
      matrix:
        channel: [stable, beta, dev]
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: 🛠️ Home Assistant configuration
        run: |
          mkdir ./test_configuration
          cp -r ./custom_components ./test_configuration
          echo "default_config:" >> ./test_configuration/configuration.yaml
          echo "tts:" >> ./test_configuration/configuration.yaml
          echo "  - platform: edge_tts" >> ./test_configuration/configuration.yaml
          echo "    language: zh-CN" >> ./test_configuration/configuration.yaml

      - name: 🏡 Home Assistant validation
        id: homeassistant
        uses: ludeeus/setup-homeassistant@main
        with:
          tag: ${{ matrix.channel }}
          config-dir: test_configuration
